### ISSUE TITLE
Can't find b() function in newest version

### ISSUE THREAD

**Issue by shadoxxhd** [Moyster/BaiGfe#1]
```
 }, S.isLeftPaneVisible = function() {
                return !("choose" === S.nvActiveAuthView && w)
            }
        }]);
    t.oobeAuthController = s
}, function(e, t, n) {
    "use strict";
    Object.defineProperty(t, "__esModule", {
        value: !0
    }), t.oobeAuthEditEmailController = void 0;
    var r = n(9);
    n(11);
    var o = r.ngOobeModule.controller("OobeAuthEditEmailController", ["$log", "jarvisService", "oobeTelemetryService", function(e, t, n) {
        function r() {
            n.updateScreen("SCREEN_OOBE_EMAIL_EDIT")
        }
```
this is the relevant section ... where exactly should I insert the fake data code?

**Comment by Moyster** [comment]
Use any software to compare your original app.js with one I modified, as stated in the readme :  

> NOTE: some of the code below might change (function letters), just compare with one of the previously uploaded app.js ;)

**Comment by shadoxxhd** [comment]
as you can see, there is no function call after the
`return !("choose" === S.nvActiveAuthView && w)
            }`
section - does this mean I should insert the new handleLoggedIn code directly after that '}' or would that break the code? I have almost no experience at all with js...

**Comment by shadoxxhd** [comment]
doing that doesn't make me able to use the software; it just shows me a black screen with all buttons disabled

**Comment by shadoxxhd** [comment]
it appears like something changed in the program logic that makes the program unusable when using your method

**Comment by shadoxxhd** [comment]
nvm, I was stupid

**Comment by Moyster** [comment]
Hehe, happens, is there a new Geforce Experience ? I installed latest 416.34 and my latest app.js still works.  
the "b()" disapeared but you can just add the fake data in the same area, just take care of "," and ";".  
(also if you're not aware, notepad++ has a really nifty "compare" plugin, I use diffuse on linux)
