### ISSUE TITLE
Manual fix for latest version

### ISSUE THREAD

**Issue by mikusHusbando** [Moyster/BaiGfe#11]
Hello. To make this work for the newest version, I looked into the source code. The manual fixes still apply, but they changed some of their function names.

```
1. Nullify login (in app.js)  

\- find :  

    if (e.domains.list.indexOf(n) > -1) return !0

\- replace by :  

    if (e.domains.list.indexOf(n) > -1) return w.handleLoggedIn(e), !0

Now let's add some fake infos, find :  

                    return !("choose" === y.nvActiveAuthView)
            }

After "}" add a new line and copy/paste this : 

                w.handleLoggedIn({
                    sessionToken: "dummySessionToken",
                    userToken: "dummyUserToken",
                    user: {
                        core: {
                            displayName: "Anonymous",
                            primaryEmailVerified: true
                        }
                    }
                });
```

**Comment by mikusHusbando** [comment]
```
- find and replace

X.isShareSupported = !1, X.isShareButtonClicked = !1

by

X.isShareSupported = !0, X.isShareButtonClicked = !0
```

**Comment by Moyster** [comment]
Hmm, the latest app.js on this repo should work on the latest GFE, I (think) I added a notice to say I'm not updating the "readme instructions" and to use some compare tools (notepad++ and the "compare" plugin, or diffuse on linux), mostly because they kept changing/renaming stuff.  
But I keep updating the app.js as soon(tm) as I notice a difference.  

What's not working for you ?

**Comment by mikusHusbando** [comment]
everything working for me after i did these patches on my newest install, but before that it didnt let me log in

**Comment by Moyster** [comment]
can you drop your app.js here ? Just drag and drop in the reply box, I'm not sure what's different than mine, thanks :) (you'll be credited for this if there's any diff)

**Comment by medama** [comment]
Isn't it y.handleLoggedIn, not w.handleLoggedIn?
That worked for me.

**Comment by Moyster** [comment]
@medama : my app.js (the one on this repo) uses y.xx, bear in mind the "instructions" in the readme can be outdated as stated :  

> Manual way :
> 
> NOTE: some of the code below might change (function letters), just compare with one of the previously uploaded app.js ;)

I'm too lazy to actually edit readme.md everytime nvidia does changes.

**Comment by Moyster** [comment]
readme should be up to date btw! closing it (feel free to reopen if i missed something)
