### ISSUE TITLE
Is there a way to disable auto-updates of GFE?

### ISSUE THREAD

**Issue by Darthagnon** [Moyster/BaiGfe#12]
GFE auto-updates, and there are instructions here and there floating around the web, saying "make this folder read only", but the structure of GFE has changed. It's also undesirable that it should auto-update, as it can occasionally break this mod.

Does anyone know how to block auto-updates on GFE v3.20.3.63?

**Comment by Darthagnon** [comment]
e.g. the current version of GFE (v3.20.3.63) downloads updates to:
```
C:\ProgramData\NVIDIA Corporation\Downloader\L0ngRand0mStr1ing0fL3ttersAndNumb3rs\
```
I have two folders named long random strings, one for Nvidia drivers updates, the other for GFE updates. Previously, I could set a folder to read only and replace a "setup.exe" with a read-only nulled version (setup.txt >> rename >> setup.exe >> replace) and that seemed to block GFE updates, but now there seems to be no generic part that I can block.

**Comment by Darthagnon** [comment]
atm, I'm trying blocking the following address via hosts (it's listed as the source of GFE updates in status.json):
```
# block Nvidia GEForce Experience updates
0.0.0.0 https://ota-downloads.nvidia.com/ota/
```

**Comment by Moyster** [comment]
Good catch, my pihole also show "ota.nvidia.com", not sure what it does yet but I'll edit the readme blocklist, thanks :)

**Comment by Darthagnon** [comment]
Thanks for adding the domain to the list (only just remembered the list existed! I've been under a rock)

Would it be worth adding it to the "lite" section, too? I think it only affects GFE updates, and it hasn't broken anything else yet (afaik).

**Comment by Moyster** [comment]
Hmm, well the point of the "lite blocklist" was to only block the telemetry, without blocking anything else.  
But as https://github.com/Moyster/BaiGfe/issues/10 pointed, the "lite" one as some issues (game list not showing most of the time) and might need to be reworked/updated.  
The full blocklist is what I personally use, the "lite blocklist" is based on the original app.js "telemetry and mandatory login" removal, and isn't really "tested" :^p  

I might update the instructions and keep only the fullblock list, but add which domains to remove based on what feature(s) people want to keep (ota.* domains for the GFE update / driver update, etc)  
For ease of installation, this might end up being a small website / form on github.io to generate a list based on what people wants.

**Comment by Darthagnon** [comment]
Thank you for the explanation! I hadn't realised the true purpose of the blocklists (thought "Full" included breaking features, while Lite maintained features working)

**Comment by Moyster** [comment]
You're welcome ;) I guess i'll add some more infos in readme to clarify what both blocklists do
