### ISSUE TITLE
3.19.0.107 - Crashing after changes (Solved)

### ISSUE THREAD

**Issue by yevgeniy-k** [Moyster/BaiGfe#13]
Version 3.19.0.107  was crashing after the changes until I removed the snippet in bold.

f.endActionAsync(r,"EMAIL_NOT_VERIFIED_RESEND_FAILED"),**S.showEmailVerification(e)**

**Comment by Moyster** [comment]
wow, that's a pretty "antique" version :^p any reason not to update?  
I'll take a look see if that change is "safe" on newer app.js and probably add it, thanks!

**Comment by yevgeniy-k** [comment]
No reason to not update. I don't use it typically and just needed to get in once. Thanks to the nice  folks at NVIDIA for not obfuscating method names!

**Comment by Moyster** [comment]
I'll apply this change from now on, thanks!
