### ISSUE TITLE
home screen have 0 game even after manual scan

### ISSUE THREAD

**Issue by magiclu** [Moyster/BaiGfe#4]
after the recent update,i am forced to login again,so i installed this,geforce experience is version 3.18.0.102,the problem is that even i manually clicked game scan,it will found few games,but i still have 0 games in the home screen of geforce experience.
i need that,because i need dsr setting
i used Auto-install easy fix  to install this
![image](https://user-images.githubusercontent.com/3338197/56112635-3fafee80-5f8e-11e9-9d7f-66dc76044703.png)

**Comment by tekwarfare** [comment]
%LOCALAPPDATA%\NVIDIA\NvBackend
Check that the two files aren't set to read-only:
journalBS.jour.dat
journalBS.main.xml

You can change the DSR in NVCP on a profile and global basis; not sure what extra GFE offers.

**Comment by magiclu** [comment]
> %LOCALAPPDATA%\NVIDIA\NvBackend
> Check that the two files aren't set to read-only:
> journalBS.jour.dat
> journalBS.main.xml
> 
> You can change the DSR in NVCP on a profile and global basis; not sure what extra GFE offers.

@tekwarfare 

journalBS.jour.dat
journalBS.main.xml
aren't set to read-only

i thought if i set global basis dsr ,some game's first time launch maybe at 8k (my monitor is 4k),i can't handle 8k,game may not open at all,so i rarely use gfe to set dsr.

i am using global basis dsr now

**Comment by Ghecko166** [comment]
Just updated to version 3.18.0.102, having the same issue. The games are detected (I can see it in the GeForce Experience settings) but do not appear in the Home tab

**Comment by Moyster** [comment]
Woops, sorry for the late answer, yeah i actually noticed it as well, most of the time GFE games are listed only when you start the app for the first time (like, a fresh boot) which is wierd :/  
I kinda lack the time to check it, but I'll try to find a moment to check next week-end.  
Maybe the changes weren't properly applied or something broke indentation, in the mean time if anyone wants to investigate, feel free to help ! :+1:

**Comment by eugenweissbart** [comment]
Any updates?

**Comment by Moyster** [comment]
Should be fixed (missing commas in nvidia's stock app.js)
