### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by fusionneur** [Moyster/BaiGfe#5]

**Comment by pix0wl** [comment]
Can't confirm that. 
I've installed Geforce Experience on my new PC for the first time, never logged in or created a account for GE and the modded app.js works superb. GE wasn't even once able to call home too, thanks to SimpleWall.

Make sure you copied the app.js to `C:\Program Files\NVIDIA Corporation\NVIDIA GeForce Experience\www`.
If it still not works provide more information.

**Comment by valuta1995** [comment]
I just tried the fix, copied the content of the JS file to the specified location. I assume you want a version number for GFX but I do not know how to get one. What other info do you need.

**Comment by ANaPhOrAX** [comment]
I have to agree with this. It doesn't work. Or let me specifiy: for me it worked ONCE, and after that, it hasn't worked AT ALL.

The first time I opened it, it worked. The second time, it didn't. It opened, but it was like "bugged" weirdly, with nothing showing, except some bugged buttons on the top left where an image was meant to load but it was grey, and it had some text there (the labels of the buttons that didn't load).

Now it's just giving me the "Something went wrong. Try restarting GeForce Experience"

**Comment by LexiconCode** [comment]
>  As of 3.15.186 app.js is reverted to stock after a reboot, make the file Read-Only ( right-click on app.js > properties > attributes : tick read-only)
