### ISSUE TITLE
doesnt work on GFE 3.20

### ISSUE THREAD

**Issue by priatnaadnyana** [Moyster/BaiGfe#7]
hi,
the app.js doesnt work anymore on latest 3.20 version 
it just stuck at this screen
https://imgur.com/gallery/TYIDaaU

any help

**Comment by GueFlo** [comment]
Did you try setting the file to readonly ?

**Comment by Moyster** [comment]
I uploaded a quick edited app.js for 3.20, but it only works after a reboot (the first time you start GFE) for some reason :/

**Comment by Moyster** [comment]
Should be fixed with the latest version (missing commas in nvidia's stock app.js)
