### ISSUE TITLE
Need a download double click fixer/patcher

### ISSUE THREAD

**Issue by dazoe** [Moyster/BaiGfe#8]
Just a small request.

**Comment by Moyster** [comment]
sorry what ?

**Comment by dazoe** [comment]
I honestly don't remember creating this issue but based on the title I think I was very tired and was wanting a simple installer utility (.exe) that would self elevate to patch the app.js file.

**Comment by Moyster** [comment]
the powershell script does that more or less, unless you want a small utility that downloads the new app.js whenever this repo is updated.
If you have a git client you can probably schedule a git fetch every night / week, so it only takes a double-click on the ps script everytime GFE updates (implying i'm not lazy and updating this repo h+1 every release :^) ).
