### ISSUE TITLE
Not working on latest GeForce Experience update

### ISSUE THREAD

**Issue by rpgwaiter** [Moyster/BaiGfe#9]
If you try to replace app.js, GeForce Experience will launch with a blank screen and you won't be able to do anything with it.

**Comment by GueFlo** [comment]
Tried the new app.js with geforce experience  3.20.2.34, game list stays blank, I hope you can fix it !

**Comment by Gonrak** [comment]
I push this probleme, thx by the way !

**Comment by Moyster** [comment]
Sometimes GFE breaks on its own, there's often some missing ";" here and there that would need to be tracked somehow (not only in app.js but in the whole nodeJS mess GFE is).  
As of the latest update (445.75 -- gfe V. 3.20.2.34 ) it looks like the "game list" is working correctly in a reliable way, so I'll close this :)
